### PR TITLE
try delete if error creating workload

### LINKED ISSUE #7: testworkload.Nginx leaks resources on failure
The `testworkload.Nginx()` method fails and returns `nil` if any of the post-creation checks fail. However, the deployment may still be created, but there is no way to destroy it.

The method should have and uphold a contract of destroying all resources it creates upon failure.

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Fixes #7 
/cc: @diegs

### CODE REVIEW

File: testworkload/nginx_workload.go [hunk 1]
```diff
@@ -107,16 +97,18 @@ func NewNginx(kc kubernetes.Interface, namespace string, options ...NginxOpts) (
...
 	}); err != nil {
-		return nil, fmt.Errorf("pods in deployment %s not ready: %v", n.Name, err)
-	}
-
-	//create nginx service
-	if err := n.newNginxService(); err != nil && !apierrors.IsAlreadyExists(err) {
-		return nil, fmt.Errorf("error creating service %s: %v", n.Name, err)
+		// try cleaning up
+		n.Delete()
+		return nil, fmt.Errorf("deployment %s is not ready: %v", n.Name, err)
```
Comment (diegs) [inline testworkload/nginx_workload.go]: Better error message? `failed to create deployment: %v` maybe?

File: testworkload/nginx_workload.go [hunk 2]
```diff
@@ -58,46 +58,36 @@ func NewNginx(kc kubernetes.Interface, namespace string, options ...NginxOpts) (
...
 	}
-
 	//apply options
 	for _, option := range options {
 		if err := option(n); err != nil {
 			return nil, fmt.Errorf("error invalid options: %v", err)
 		}
 	}
 
-	//create nginx deployment
```
Comment (diegs) [inline testworkload/nginx_workload.go:69]: I would move create() calls out of the poll loop (and create the service and deployment together). Client-go already has built-in retries for create calls, no need to duplicate that. I'd actually fail hard if the deployment already exists.

Then I'd have your two checks in a poll loop. Not sure why you need the checks (you're validating that kubernetes does its job?). But those are loop-worthy.

One way to organize this would be to have a `var err error` at the top, and `defer` an anonymous cleanup function to delete if `err` is non-nil.

Then you just bail at any error and cleanup will always get called. The only trick is to be careful with the scope of err, since it's easy to override it.

File: testworkload/nginx_workload.go [hunk 3]
```diff
@@ -58,46 +58,36 @@ func NewNginx(kc kubernetes.Interface, namespace string, options ...NginxOpts) (
...
-	if err := n.newNginxDeployment(); err != nil && !apierrors.IsAlreadyExists(err) {
-		return nil, fmt.Errorf("error creating deployment %s: %v", n.Name, err)
-	}
 	if err := wait.PollImmediate(PollIntervalForNginx, PollTimeoutForNginx, func() (bool, error) {
+		//create nginx deployment
```
Comment (diegs) [inline testworkload/nginx_workload.go]: this comment is kind of redundant, the next line says exactly the same thing (same with `newNginxService()`)

File: testworkload/nginx_workload.go (hunk 2 above)
Comment (abhinavdahiya) [reply testworkload/nginx_workload.go:69]: @diegs made some changes. let me know if this is better.

Comment (diegs) [reply testworkload/nginx_workload.go:69]: I think it's much cleaner, thanks!

**Review by diegs — APPROVED** [review]
